### ISSUE TITLE
TaleLearnCode

### ISSUE THREAD

**Issue by TaleLearnCode** [tbd-develop/developers.stream#20]
*What is your twitch/youtube channel name?*
TaleLearnCode

*Url?*
https://twitch.tv/talelearncode
https://www.youtube.com/channel/UChdTJpfJ_iIXw78bPm01MXQ

*What sort of things do you stream about? (Games, Websites)*
TALEs about software development; LEARNING from each other; CODE to build solutions

*What languages/technologies that you use might help people find you?*
C#/.NET/Azure

*How did you hear about developers.stream?*
Watching tbdgamer

**Comment by tbd-develop** [comment]
Sorry this took so long to complete.
